# Generated by Django 4.2.16 on 2024-09-09 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PastryItem',
            new_name='Product',
        ),
    ]
